spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres-animal-inst:5432/postgres-animal
    username: postgres-animal
    password: postgres-animal
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update