spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres-client-inst:5432/postgres-client
    username: postgres-client
    password: postgres-client
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update